name: restore
version: 1.0.0
summary: "Restore configuration and session data from backup"

triggers: ["/restore"]

args:
  - name: args
    type: string
    required: false
    help: "Command arguments (supports --flags)"

stdin: true
stdout:
  type: text

security:
  scope: user
  allow_remote: false
  resources:
    timeout_ms: 15000
    max_stdout_kib: 16

runtime:
  entry: "run.py"
  interpreter: "python"

telemetry:
  log_invocation: true
  log_output: false

examples:
  - "/restore --file config_backup_2025-10-23.zip"
  - "/restore --file session_backup.zip"