name: sync
version: 1.0.0
summary: Force synchronization of queued commands to cloud
description: Force synchronization of queued commands to cloud
triggers:
  - /sync
  - /s
aliases:
  - /sync
  - /s
security:
  resources:
    timeout_ms: 30000
    max_stdout_kib: 64
    max_stderr_kib: 16
  capabilities:
    - network
    - filesystem
examples:
  - "/sync - Force sync all queued commands to cloud"
  - "/sync --dry-run - Show what would be synced without actually syncing"
  - "/s - Short alias for sync command"