name: workspace
version: 1.0.0
status: stable
summary: "Manage isolated workspaces"

triggers: ["/workspace"]

dependencies:
  packages: []
  api_keys: []

args:
  - name: list
    type: bool
    required: false
    help: "List all workspaces"
  - name: create
    type: string
    required: false
    help: "Create a new workspace with the given name"
  - name: switch
    type: string
    required: false
    help: "Switch to the specified workspace"
  - name: delete
    type: string
    required: false
    help: "Delete the specified workspace"
  - name: add-collection
    type: string
    required: false
    help: "Add xAI collection to an existing workspace"
  - name: venv
    type: bool
    required: false
    help: "Create virtual environment when creating workspace"
  - name: collection
    type: bool
    required: false
    help: "Create xAI collection when creating workspace"
  - name: preserve_collection
    type: bool
    required: false
    help: "Preserve xAI collection when deleting workspace"

stdin: false
stdout:
  type: text

security:
  scope: user
  allow_remote: false
  resources:
    timeout_ms: 30000
    max_stdout_kib: 64

runtime:
  entry: "run.py"
  interpreter: "python"

telemetry:
  log_invocation: true
  log_output: false

examples:
  - "/workspace --list"
  - "/workspace --create myproject"
  - "/workspace --create myproject --venv"
  - "/workspace --create myproject --venv --collection"
  - "/workspace --add-collection myproject"
  - "/workspace --switch myproject"
  - "/workspace --delete myproject"
