name: workspace
version: 1.0.0
summary: "Manage isolated workspaces for safe bot operations"

triggers: ["/workspace"]

args:
  - name: subcommand
    type: string
    required: true
    help: "Subcommand: create, list, switch, delete"
  - name: name
    type: string
    required: false
    help: "Workspace name (for create, switch, delete)"
  - name: venv
    type: bool
    required: false
    help: "Create virtual environment in workspace (create only)"
  - name: collection
    type: bool
    required: false
    help: "Create xAI collection for workspace (create only)"
  - name: preserve-collection
    type: bool
    required: false
    help: "Preserve xAI collection when deleting workspace (delete only)"

stdin: true
stdout:
  type: text

security:
  scope: user
  allow_remote: false
  resources:
    timeout_ms: 10000
    max_stdout_kib: 64

runtime:
  entry: "run.py"
  interpreter: "python"

telemetry:
  log_invocation: true
  log_output: false
  redact_patterns: []

examples:
  - "/workspace create myproject - Create new workspace"
  - "/workspace create myproject --venv - Create workspace with virtual environment"
  - "/workspace create myproject --collection - Create workspace with xAI collection"
  - "/workspace create myproject --venv --collection - Create workspace with both venv and collection"
  - "/workspace list - List all workspaces"
  - "/workspace switch myproject - Switch to workspace"
  - "/workspace delete myproject - Delete workspace and its collection"
  - "/workspace delete myproject --preserve-collection - Delete workspace but keep collection"