name: backup
version: 1.0.0
summary: "Backup configuration and session data"

triggers: ["/backup"]

args:
  - name: args
    type: string
    required: false
    help: "Command arguments (supports --flags)"

stdin: false
stdout:
  type: text

security:
  scope: user
  allow_remote: false
  resources:
    timeout_ms: 10000
    max_stdout_kib: 16

runtime:
  entry: "run.py"
  interpreter: "python"

telemetry:
  log_invocation: true
  log_output: false

examples:
  - "/backup"
  - "/backup --target config"
  - "/backup --target session"