name: help
version: 1.0.0
status: stable
summary: "Display command reference or detailed help for specific command"
description: |
  Shows available commands and usage. Can provide detailed help for specific commands.

triggers: ["/help"]
aliases: ["/h"]

dependencies:
  packages: []
  api_keys: []

args:
  - name: command
    type: string
    required: false
    help: "Command name for detailed help"

stdin: false
stdout:
  type: text

security:
  scope: user
  allow_remote: true
  resources:
    timeout_ms: 1000
    max_stdout_kib: 16

runtime:
  entry: "run.py"
  interpreter: "python"

telemetry:
  log_invocation: true
  log_output: false

examples:
  - "/help"
  - "/help /config"