name: alias
version: 1.0.0
summary: Manage Unix-to-PowerShell command aliases
description: Manage Unix-to-PowerShell command aliases
usage: /alias [--list|--show <cmd>|--enable|--disable|--add <unix> <ps>|--remove <unix>]
triggers:
  - /alias
args:
  - name: args
    type: string
    required: false
    help: "Command arguments (supports --flags)"
stdin: false
stdout:
  type: text
security:
  scope: user
  allow_remote: true
  resources:
    timeout_ms: 5000
    max_stdout_kib: 64
runtime:
  entry: run.py
  interpreter: python