name: mine
version: 1.0.0
summary: Personal file history and collection search
description: |
  Search your personal file history (Total Commander logs, project snapshots)
  using xAI Collections. This is YOUR stuff, not internet knowledge.

triggers:
  - /mine

aliases:
  - /mine

args:
  - name: create
    type: string
    required: false
    help: "Create new collection with the given name"
  - name: use
    type: string
    required: false
    help: "Switch to the specified collection"
  - name: delete
    type: string
    required: false
    help: "Delete the specified collection"
  - name: upload
    type: string
    required: false
    help: "Upload file to active collection"
  - name: search
    type: string
    required: false
    help: "Search active collection for the given query"
  - name: list
    type: bool
    required: false
    help: "List all collections"
  - name: maps
    type: bool
    required: false
    help: "List all collections (alias for --list)"
  - name: info
    type: bool
    required: false
    help: "Show active collection details"
  - name: status
    type: bool
    required: false
    help: "Show system status"
  - name: help
    type: bool
    required: false
    help: "Show help information"

stdin: true
stdout:
  type: text

security:
  scope: user
  allow_remote: true
  resources:
    timeout_ms: 30000
    max_stdout_kib: 1024
  capabilities:
    - network

examples:
  - "/mine --list - List all collections"
  - "/mine --create mydocs - Create new collection"
  - "/mine --use mydocs - Switch to collection"
  - "/mine --upload file.txt - Upload file to active collection"
  - "/mine --search 'what is machine learning?' - Search active collection"
  - "/mine --info - Show active collection details"